<img src="https://github.com/jelenavasic009-png/DSB-Unit-02/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Introduction to `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Explore the characteristics of a dataset at a high level with `pandas`.

### Notebook Guide
An exercise in practising:

- Reading data with `pandas`
- Exploring and manipulating data with `pandas`
    - Column operations
    - Filtering
    - Sorting
    - Writing data

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

### Business question

What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

#### 1. Import `pandas` and read in the LEGO dataset

In [8]:
import pandas as pd

In [9]:
url = 'https://raw.githubusercontent.com/juanatga/intro-to-eda-and-pandas/main/data/lego.csv'
import pandas as pd
lego_df = pd.read_csv(url)

#### 2. So we can focus on just the columns that help answer the question, select only the following columns into a new `DataFrame` variable:

- name
- theme
- number of pieces
- retail price (USD_MSRP)

In [11]:
lego_df.columns

Index(['Set_ID', 'Name', 'Year', 'Theme', 'Theme_Group', 'Subtheme',
       'Category', 'Packaging', 'Num_Instructions', 'Availability', 'Pieces',
       'Minifigures', 'Owned', 'Rating', 'USD_MSRP', 'Total_Quantity',
       'Current_Price'],
      dtype='object')

In [13]:
short_lego_df = lego_df[['Name', 'Theme','Pieces','USD_MSRP']]
short_lego_df

                          Name      Theme  Pieces  USD_MSRP
0                PreSchool Set  PreSchool    16.0       NaN
1                PreSchool Set  PreSchool    20.0       NaN
2               Pre-School Set      Duplo    21.0       NaN
3                PreSchool Set  PreSchool    32.0       NaN
4                    Basic Set  Samsonite   330.0       NaN
...                        ...        ...     ...       ...
14931        Creeper Key Chain       Gear     NaN      5.99
14932          Steve Key Chain       Gear     NaN      5.99
14933         Piglin Key Chain       Gear     NaN      5.99
14934   Fennec Shand Key Chain       Gear     NaN      5.99
14935  Scout Trooper Key Chain       Gear     NaN      5.99

[14936 rows x 4 columns]

#### 3. How many sets have a price greater than $100?

In [16]:
cijene = short_lego_df[C] #nova varijabila u uzete sve cijene vece od 100
short_lego_df[cijene > 100]

#greater_than_100 = sort_lego_dg [short_lego_df[V] > 100]

                            Name          Theme  Pieces  USD_MSRP
4769     Imperial Star Destroyer      Star Wars  3096.0    269.99
5324            3-Seat Playtable           Gear     NaN    249.99
5973               Death Star II      Star Wars  3441.0    269.99
5974                 Sandcrawler      Star Wars  1669.0    139.99
6256          Cargo Train Deluxe           City   856.0    149.99
...                          ...            ...     ...       ...
14896  Temple of the Golden Idol  Indiana Jones  1545.0    149.99
14900  Monkie Kid's Team Hideout     Monkie Kid  1582.0    139.99
14901     Monkey King Ultra Mech     Monkie Kid  1705.0    159.99
14905  Dragon of the East Palace     Monkie Kid  2364.0    189.99
14907      Lunar New Year Parade       Seasonal  1653.0    129.99

[380 rows x 4 columns]

#### 4. What are the top 10 sets with the highest number of pieces?

In [17]:
short_lego_df.info() #prvo trazimo da vidimo sta sve ima baza sa podacima

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      14936 non-null  object
 1   Theme     14936 non-null  object
 2   Pieces    13133 non-null  float64
 3   USD_MSRP  5837 non-null   float64
dtypes: float64(2), object(2)
memory usage: 466.9+ KB

In [19]:
short_lego_df.sort_values ('Pieces',ascending=False).head(10)

                                   Name           Theme   Pieces  USD_MSRP
13559                         World Map             Art  11695.0    249.99
13946                      Eiffel Tower           Icons  10001.0    629.99
13449                           Titanic           Icons   9090.0    679.99
12942                         Colosseum           Icons   9036.0    549.99
11928                 Millennium Falcon       Star Wars   7541.0    849.99
14380                   The Razor Crest       Star Wars   6187.0    599.99
14440  The Lord of the Rings: Rivendell           Icons   6167.0    499.99
14807              NINJAGO City Markets         Ninjago   6163.0    369.99
12369                   Hogwarts Castle    Harry Potter   6020.0    469.99
11437                         Taj Mahal  Creator Expert   5923.0    369.99

#### 5. Create a new column to measure "price per piece", which should be the price (USD_MSRP) divided by the number of pieces

In [20]:
short_lego_df['Price_per_piece'] = short_lego_df['USD_MSRP'] /short_lego_df['Pieces']
short_lego_df

#short_lego_df['Price_per_piece'] = short_lego_df['USD_MSRP']/ short_lego_df['Pieces']

/tmp/ipykernel_3047/1893463503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  short_lego_df['Price_per_piece'] = short_lego_df['USD_MSRP'] /short_lego_df['Pieces']

                          Name      Theme  Pieces  USD_MSRP  Price_per_piece
0                PreSchool Set  PreSchool    16.0       NaN              NaN
1                PreSchool Set  PreSchool    20.0       NaN              NaN
2               Pre-School Set      Duplo    21.0       NaN              NaN
3                PreSchool Set  PreSchool    32.0       NaN              NaN
4                    Basic Set  Samsonite   330.0       NaN              NaN
...                        ...        ...     ...       ...              ...
14931        Creeper Key Chain       Gear     NaN      5.99              NaN
14932          Steve Key Chain       Gear     NaN      5.99              NaN
14933         Piglin Key Chain       Gear     NaN      5.99              NaN
14934   Fennec Shand Key Chain       Gear     NaN      5.99              NaN
14935  Scout Trooper Key Chain       Gear     NaN      5.99              NaN

[14936 rows x 5 columns]

#### 6. Use this column to find the top 10 most expensive sets by "price per piece"

In [22]:
short_lego_df.sort_values('Price_per_piece',ascending=False).head(10)

,Name,Theme,Pieces,USD_MSRP,Price_per_piece
13892,Character Pack Series 3 - Complete,Super Mario,0.0,4.99,inf
13806,LEGO Minifigures - Marvel Studios Series {Box ...,Collectable Minifigures,0.0,29.94,inf
14251,LEGO Minifigures - Series 22 {Box of 6 random ...,Collectable Minifigures,0.0,29.94,inf
9653,EV3 Intelligent Brick,Mindstorms,1.0,224.95,224.950
6342,NXT Intelligent Brick,Mindstorms,1.0,169.99,169.990
7695,Intelligent NXT Brick (Black),Mindstorms,1.0,169.99,169.990
13755,Small Hub,Education,2.0,214.95,107.475
9654,DC Rechargeable Battery,Education,1.0,99.95,99.950
8197,NXT DC Rechargeable Battery,Education,1.0,79.99,79.990
12927,Boost Hub,Powered Up,1.0,79.99,79.990

#### 7. Narrow the search to show the top 10 most expensive sets by "price per piece" for the "Icons" theme *only*

In [25]:
icon_descending = short_lego_df.sort_values('Price_per_piece', ascending=False)
condition =icon_descending['Theme'] == 'Icons'
icon_descending[condition].head(10)

,Name,Theme,Pieces,USD_MSRP,Price_per_piece
13941,Optimus Prime,Icons,1508.0,179.99,0.119357
13943,Chevrolet Camaro Z/28 1969,Icons,1456.0,169.99,0.116751
13450,Porsche 911,Icons,1458.0,169.99,0.116591
13440,Adidas Originals Superstar,Icons,731.0,79.99,0.109425
13939,Back to the Future Time Machine,Icons,1872.0,199.99,0.106832
13942,Loop Coaster,Icons,3756.0,399.99,0.106494
14441,Land Rover Classic Defender 90,Icons,2336.0,239.99,0.102735
13446,Queer Eye – The Fab 5 Loft,Icons,974.0,99.99,0.102659
12940,Ghostbusters ECTO-1,Icons,2352.0,239.99,0.102037
13617,Everyone is Awesome,Icons,346.0,34.99,0.101127

#### 8. What are the top 10 cheapest sets by "price per piece" in the "Icons" theme?

In [27]:
#icon_descending = short_lego_df.sort_values('Price_per_piece', ascending=False)
#condition =icon_descending['Theme'] == 'Icons'
icon_descending[condition].tail(10)

,Name,Theme,Pieces,USD_MSRP,Price_per_piece
13598,Mini Adidas Originals Superstar,Icons,92.0,NaN,NaN
13940,{?},Icons,NaN,NaN,NaN
13949,{?},Icons,NaN,NaN,NaN
14086,Vintage Taxi,Icons,163.0,NaN,NaN
14117,Forest Hideout,Icons,258.0,NaN,NaN
14127,Eiffel's Apartment,Icons,228.0,NaN,NaN
14439,{?},Icons,NaN,NaN,NaN
14539,Blacktron Cruiser,Icons,356.0,NaN,NaN
14540,BIONICLE Tahu and Takua,Icons,219.0,NaN,NaN
14545,Moving Truck,Icons,301.0,NaN,NaN

#### 9. Export the `DataFrame` you created in question 2. to a new CSV file.

In [28]:
short_lego_df.to_csv("JelenaVasic.csv", index=False)

#da se u EXcel-u ukloni kolona koja pocinje od ,0'

### Reflection

What is your answer to the business question? Here it is as a reminder:

> What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

Reflect on your experience. How was working with `pandas` compared to other tools you already know?